# This compose file is for local development/deployment only. But you may use it as an example for a production setup.

# Postgres database
services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network